import { MigrationRule } from "./types";
import { scanOpenAIModels } from "../scanners/openaiScanner";
import { migrateOpenAIModels } from "../migrators/openaiModelMigrator";

export const openAIModelRule: MigrationRule = {
  id: "openai-model-rename",
  description: "Migrate deprecated OpenAI model gpt-3.5-turbo",

  async scan(root: string) {
    return scanOpenAIModels(root);
  },

  async migrate(findings) {
    if (findings.length === 0) return false;
    await migrateOpenAIModels(findings);
    return true;
  },

  pr: {
    branch: "migratekit/openai-model",
    title: "Update deprecated OpenAI model",
    body:
      "This PR was automatically generated by MigrateKit.\n\n" +
      "Changes:\n" +
      "- Replaced `gpt-3.5-turbo` with `gpt-4.1-mini`\n\n" +
      "⚠️ Manual review recommended for output quality and token usage.",
    humanReviewNotes:
      "Validate responses, latency, and cost after model upgrade."
  }
};
