import { MigrationRule } from "./types";
import { scanStripeCharges } from "../scanners/stripeScanner";
import { migrateStripeCharges } from "../migrators/stripeChargesMigrator";

export const stripeChargesRule: MigrationRule = {
  id: "stripe-charges",
  description: "Migrate stripe.charges.create to paymentIntents",

  async scan(root: string) {
    return scanStripeCharges(root);
  },

  async migrate(findings) {
    if (findings.length === 0) return false;
    await migrateStripeCharges(findings);
    return true;
  },

  pr: {
    branch: "migratekit/stripe-charges",
    title: "Migrate Stripe Charges to Payment Intents",
    body:
      "This PR was automatically generated by MigrateKit.\n\n" +
      "Changes:\n" +
      "- Replaced stripe.charges.create with stripe.paymentIntents.create\n\n" +
      "⚠️ Manual review required for payment flow behavior.",
    humanReviewNotes:
      "Verify confirmation flows, webhooks, and client secret handling."
  }
};
