import { scanStripeCharges } from "../scanners/stripeScanner";
import { migrateStripeCharges } from "../migrators/stripeChargesMigrator";
import { createPullRequest } from "../pr/github";

export async function runAgent(ctx: {
  migrationType: string;
  repoPath: string;
}) {
  console.log(`🧠 Agent running for migration: ${ctx.migrationType}`);

  if (ctx.migrationType !== "stripe-charges") {
    console.log("❌ Unsupported migration type");
    return;
  }

  const findings = scanStripeCharges(ctx.repoPath);
  
  if (findings.length === 0) {
    console.log("✅ No deprecated Stripe usage found");
    return;
  }

  console.log(`⚠️ Found ${findings.length} deprecated Stripe usages`);

  console.log(`⚠️ Found ${findings.length} deprecated Stripe usages`);

findings.forEach(f => {
  console.log(`${f.file}:${f.line} → ${f.code}`);
});

migrateStripeCharges(findings);

console.log("✅ Migration complete");
const token = process.env.INPUT_GITHUB_TOKEN;

if (!token) {
  throw new Error("Missing GitHub token");
}

await createPullRequest(
  token,
  "migratekit/stripe-charges",
  "Migrate Stripe Charges to Payment Intents",
  "This PR was automatically generated by MigrateKit.\n\n" +
    "Changes:\n" +
    "- Replaced stripe.charges.create with stripe.paymentIntents.create\n\n" +
    "⚠️ Manual review required for payment flow behavior."
);
}
